# Generated by Django 3.2.2 on 2021-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='slug_user',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='URL'),
        ),
    ]
