# Generated by Django 3.2.2 on 2021-05-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Категория')),
                ('slug_category', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описаине')),
                ('slug_order', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('pricer', models.IntegerField(verbose_name='Цена')),
                ('publication', models.BooleanField(default=False, verbose_name='Публикация')),
                ('publication_date', models.DateTimeField(blank=True, verbose_name='Дата публикации')),
                ('stage', models.IntegerField(default=1, verbose_name='Этап')),
                ('occupancy', models.IntegerField(default=0, verbose_name='Заполняемост')),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='photo/orders/%Y/%m/%d', verbose_name='Фото')),
                ('documents', models.ImageField(blank=True, upload_to='documents/<django.db.models.fields.SlugField>/%Y/%m/%d', verbose_name='Документы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['title', '-publication'],
            },
        ),
        migrations.CreateModel(
            name='OrderStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Orders.categories', verbose_name='Категории заказов')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders', verbose_name='Заказы')),
                ('rolls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Роли пользователей')),
            ],
        ),
    ]
