# Generated by Django 3.2.2 on 2021-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_orders_slug_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
