# Generated by Django 3.2.2 on 2021-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_orderstaff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstaff',
            name='categories',
            field=models.CharField(blank=True, max_length=255, verbose_name='Категории заказов'),
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='rolls',
            field=models.CharField(blank=True, max_length=255, verbose_name='Роли пользователей'),
        ),
    ]
